---
output: pdf_document
params:
    rseed: 0
    showsol: true
---

```{r,echo=F,warning=FALSE,message=FALSE}
if(params$rseed !=0){
    set.seed(params$rseed)
}

pn = function(coeffs,pows){
    pows = pows[coeffs!=0]
    coeffs = coeffs[coeffs!=0]
    ex1 = paste0("{",coeffs,"}x^{",pows,"}",collapse="+")
    ex1 = gsub("+{-","-{",ex1,fixed=T)
    ex1 = gsub("{1}x^{0}","1",ex1,fixed=T)
    ex1 = gsub("{-1}x^{0}","-1",ex1,fixed=T)
    ex1 = gsub("{1}x","x",ex1,fixed=T)
    ex1 = gsub("{-1}x","-x",ex1,fixed=T)
    ex1 = gsub("x^{0}","",ex1,fixed=T)
    ex1 = gsub("x^{1}","x",ex1,fixed=T)
    ex1 = gsub("+-","-",ex1,fixed=T)
    if(ex1 == ""){
        ex1 = "0"
    }
    return(ex1)
}
gcd2 <- function(a, b) {
    if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))
```

Name: \vspace{5pt} \hrule

## a1223p_graph_quadratics (v`r params$rseed`)

```{r,echo=F}
library(MASS)
# as = numeric()
hs = numeric()
ks = numeric()
eqs = character()
abba = c(2,3,1/2,1/3,1/4,1/9)
as = sample(c(abba,-abba),8)
qtextra = sample(1:3,2)
qts = sample(c(1:3,1:3,qtextra))

for(i in 1:8){
    a = as[i]
    qt = qts[i]
    if(qt==1){
        h = sample(1:7,1)*sample(c(-1,1),1)
        k = sample(1:7,1)*sample(c(-1,1),1)
        if(abs(a)>1){
            eq = paste0(a,"(x+",-h,")^2+",k,collapse="")
        } else {
            eq = paste0("\\frac{",sign(a),"}{",abs(round(1/a)),"}(x+",-h,")^2+",k,collapse="")
        }
        eq = gsub("+-","-",eq,fixed=T)
    }
    
    if(qt==2){
        while(T){
            RS = sample(1:10,2)*sample(c(-1,1),2,T)
            r = RS[1]
            s = RS[2]
            if(abs(a)>1){
                eq = paste0(a,"(x+",-r,")(x+",-s,")",collapse="")
            } else {
                eq = paste0("\\frac{",sign(a),"}{",abs(round(1/a)),"}(x+",-r,")(x+",-s,")",collapse="")
            }
            eq = gsub("+-","-",eq,fixed=T)
            h = (r+s)/2
            w = abs(r-s)/2
            k = round(-a*w^2,5)
            if(abs(k)<11 && abs(k)%%1==0 && abs(h)%%1==0){break}
        }
    }
    if(qt==3){
        while(T){
            h = sample(1:6,1)*sample(c(-1,1),1)
            b = -2*a*h
            c = sample(1:9,1)*sample(c(-1,1),1)
            k = a*h^2+b*h+c
            if(b%%1!=0){
                bb = paste0("\\frac{",gsub("/","}{",fractions(b),fixed=T),"}")
            } else {
                bb = paste0(b)
            }
            if(abs(a)>1){
                eq = paste0(a,"x^2+",bb,"x+",c,collapse="")
            } else {
                eq = paste0("\\frac{",sign(a),"}{",abs(round(1/a)),"}x^2+",bb,"x+",c,collapse="")
            }
            eq = gsub("+-","-",eq,fixed=T)
            eq = gsub("+\\frac{-","-\\frac{",eq,fixed=T)
            eq = gsub("+1x","+x",eq,fixed=T)
            eq = gsub("-1x","-x",eq,fixed=T)
            if(abs(k)<11 && abs(k)%%1==0 && abs(h)%%1==0){break}
        }
    }
    hs = c(hs,h)
    ks = c(ks,k)
    eqs = c(eqs,eq)
}

```

Graph each of the quadratic equations. Accurately mark **all lattice points** along the curve with filled dots.

```{r,echo=F,fig.dim=c(6.5,7.5)}
library(latex2exp)
par(mar=c(1,0,3,0),pty="s",mfrow=c(2,2))
for(i in 1:4){
    a = as[i]
    h = hs[i]
    k = ks[i]
    plot(0,0,"n",xlim=c(-11,11),ylim=c(-11,11),axes=F,ann=F)
    mtext(TeX(paste0("$y=",eqs[i],"$")),3)
    for(j in -10:10){
        lines(c(-10,10),c(j,j),col="grey",lwd=0.5)
        lines(c(j,j),c(-10,10),col="grey",lwd=0.5)
    }
    for(j in seq(-10,10,5)){
        lines(c(-10,10),c(j,j),col="darkgrey",lwd=1)
        lines(c(j,j),c(-10,10),col="darkgrey",lwd=1)
    }
    arrows(-11,0,11,0,0.05,20,3,lwd=1.5)
    arrows(0,-11,0,11,0.05,20,3,lwd=1.5)
    if(params$showsol){
        x = seq(-10,10,0.01)
        y = a*(x-h)^2+k
        x = x[abs(y)<=10]
        y = y[abs(y)<=10]
        lines(x,y,col="red",lwd=2)
        # x = seq(-10,10,1)
        x = -10:10
        y = a*(x-h)^2+k
        x = x[abs(y)<=10]
        y = y[abs(y)<=10]
        x = x[abs(y)%%1==0]
        y = y[abs(y)%%1==0]
        points(x,y,col="red",pch=19)
    }
}

```


\newpage


## a1223p_graph_quadratics (v`r params$rseed`)

Graph each of the quadratic equations. Accurately mark **all lattice points** along the curve with filled dots.


```{r,echo=F,fig.dim=c(6.5,8)}
library(latex2exp)
par(mar=c(1,0,3,0),pty="s",mfrow=c(2,2))
for(i in 5:8){
    a = as[i]
    h = hs[i]
    k = ks[i]
    plot(0,0,"n",xlim=c(-11,11),ylim=c(-11,11),axes=F,ann=F)
    mtext(TeX(paste0("$y=",eqs[i],"$")),3)
    for(j in -10:10){
        lines(c(-10,10),c(j,j),col="grey",lwd=0.5)
        lines(c(j,j),c(-10,10),col="grey",lwd=0.5)
    }
    for(j in seq(-10,10,5)){
        lines(c(-10,10),c(j,j),col="darkgrey",lwd=1)
        lines(c(j,j),c(-10,10),col="darkgrey",lwd=1)
    }
    arrows(-11,0,11,0,0.05,20,3,lwd=1.5)
    arrows(0,-11,0,11,0.05,20,3,lwd=1.5)
    if(params$showsol){
        x = seq(-10,10,0.01)
        y = a*(x-h)^2+k
        x = x[abs(y)<=10]
        y = y[abs(y)<=10]
        lines(x,y,col="red",lwd=2)
        # x = seq(-10,10,1)
        x = -10:10
        y = a*(x-h)^2+k
        x = x[abs(y)<=10]
        y = y[abs(y)<=10]
        x = x[y%%1==0]
        y = y[y%%1==0]
        points(x,y,col="red",pch=19)
    }
}

```

