---
title: "Sub Plans for Worley on Mon Feb 03"
output: 
    pdf_document:
        toc: true
urlcolor: blue

---


## Algebra 2 8:00-9:05 in Marquez 409

* Students have a few "quizzes" on Canvas.
* If you are mathematically inclined, you can work through some examples:
    * [https://artockthedino.github.io/algtwo2026/u08/0203/examples_0203.html](https://artockthedino.github.io/algtwo2026/u08/0203/examples_0203.html)

## Math Literacy 10:06 - 11:01 in Marquez 409

* Students will review SOHCAHTOA
    * [https://mathworld.wolfram.com/SOHCAHTOA.html](https://mathworld.wolfram.com/SOHCAHTOA.html)
* Students will complete a solo Blooket
    * [https://play.blooket.com/play?hwId=698165fcedf6fdd5a4ce4067](https://play.blooket.com/play?hwId=698165fcedf6fdd5a4ce4067)
    * This Blooket will close today. No late submissions will be accepted.
    * Students can help each other.

## Algebra 2 11:04-12:01 in Carson 301

* Students have a few "quizzes" on Canvas.
* If you are mathematically inclined, you can work through some examples:
    * [https://artockthedino.github.io/algtwo2026/u08/0203/examples_0203.html](https://artockthedino.github.io/algtwo2026/u08/0203/examples_0203.html)
    
## Crew (Community Meeting) 12:04 - 12:31 in Gym

* Hang out with some Juniors.

## Project Based Learning 2:02-2:57 in Mondrian 205

* There is an entrance ticket on Canvas. (10 minutes or so)
* There is a project assignment on Canvas. Students will make a frieze-pattern slideshow using [google slides](slides.new). The project is described on Canvas.
    * Exemplar: [https://artockthedino.github.io/pbl/daily/day04/Frieze_slideshow_exemplar.html](https://artockthedino.github.io/pbl/daily/day04/Frieze_slideshow_exemplar.html)
    * Students should use this tool to generate the patterns:
        * [https://chadworley.github.io/frieze/frieze.html](https://chadworley.github.io/frieze/frieze.html)
    * Students should create 7 patterns, one of each frieze group. They will screenshot their results to put them into the slideshow.
    * The slideshow should have 8 slides. The first slide is a title slide with the project title and their name. Then there should be one slide per frieze pattern.
    * Each slide will say the [frieze group name](https://en.wikipedia.org/wiki/Frieze_group#Descriptions_of_the_seven_frieze_groups).
    * Each slide will say something about the pattern.
        * What was your process?
        * What does it remind you of?
    * Students will struggle to submit their slideshows. They should first download their slides as a PDF. Then, on the Canvas assignment, they can upload the PDF and submit it.
    * STUDENTS SHOULD NOT SHARE THE SLIDES WITH ME. They should submit the slides on Canvas. They will lose points if they share their slides with me.


