---
output: pdf_document
params:
    rseed: 0
    showsol: false
---

```{r,echo=F,warning=FALSE,message=FALSE}
options(scipen=999)
if(params$rseed !=0){
    set.seed(params$rseed)
}
knitr::opts_chunk$set(echo = FALSE)
bn <- basename(knitr::current_input())
bn = strsplit(bn,".",fixed=T)[[1]][1]
```

Name: \vspace{5pt} \hrule

## `r bn` (v`r params$rseed`)

```{r}
gcd2 <- function(a, b) {
  if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))
e1s = character()
e2s = character()
while(length(e2s)<8){
    while(T){
        abcd = sample(c(2:9),4)*sample(c(-1,1),1)
        gg1 = gcd(abs(abcd))
        a = abcd[1]/gg1
        b = abcd[2]/gg1
        c = abs(abcd[3]/gg1)
        d = abcd[4]/gg1
        e1 = paste0("\\frac{",a,"+",b,"i}{",c,"+",d,"i}")
        e1 = gsub("+-","-",e1,fixed=T)
        r = a*c+b*d
        q = b*c-a*d
        n = c^2+d^2
        gg2 = gcd(abs(c(r,q,n)))
        r2 = r/gg2
        q2 = q/gg2
        n2 = n/gg2
        e2 = paste0("\\frac{",r2,"+",q2,"i}{",n2,"}")
        e2 = gsub("+-","-",e2,fixed=T)
        if(min(abs(c(r2,q2,n2)))>1 && max(abs(c(r,q,n)))<50){break}
    }
    e3 = paste0("\\frac{(",a,"+",b,"i)(",c,"+",-d,"i)}{(",c,"+",d,"i)(",c,"+",-d,"i)}")
    e3 = gsub("+-","-",e3,fixed=T)
    e4 = paste0("\\frac{",a*c,"+",-a*d,"i+",b*c,"i+",-b*d,"i^2}{",c^2,"+",-c*d,"i+",c*d,"i+",-d^2,"i^2}")
    e4 = gsub("+-","-",e4,fixed=T)
    e5 = paste0("\\frac{",a*c,"+",-a*d,"i+",b*c,"i+",b*d,"}{",c^2,"+",-c*d,"i+",c*d,"i+",d^2,"}")
    e5 = gsub("+-","-",e5,fixed=T)
    e6 = paste0("\\frac{",a*c+b*d,"+",-a*d+b*c,"i}{",c^2+d^2,"}")
    e6 = gsub("+-","-",e6,fixed=T)
    ans = paste0("(",r2,"+",q2,"i)/",n2)
    ans = gsub("+-","-",ans,fixed=T)
    if(!(e2 %in% e2s)){
        e1s = c(e1s,e1)
        e2s = c(e2s,e2)
    }
}
```



```{r,results='asis'}

for(i in 1:length(e1s)){
    cat(paste0(i,". Rationalize the complex denominator. Reduce the fraction.$$",e1s[i],"$$\n\n\\vfill\n\n"))
    if(params$showsol){
        cat(paste0("\\color{red}\n\n$$",e2s[i],"$$\n\n\\vfill\\color{black}\n\n"))
    }
    cat("\\vfill\n\n")
    if(i == floor(length(e1s)/2)){
        cat("\\newpage\n\n")
    }
}

if(!(params$showsol)){
        cat("\\color{gray}\n")
        cat(paste0("$",sample(e2s),"$",collapse=", "))
        cat("\n\n\\color{black}")
    }


```


