```{r,echo=FALSE}
ab = sample(11:99,2)

a = ab[1]
b = ab[2]
c = round(sqrt(a^2+b^2))
b = sqrt(c^2-a^2)

```

Question
========

On the right triangle below, find the length of the missing side.


```{r,echo=F,fig.dim=c(4,4)}
x0 = c(-2/3*b,1/3*b,1/3*b)
y0 = c(-1/3*a,-1/3*a,2/3*a)
r0 = sqrt(x0^2+y0^2)
r0max = max(r0)

bsize = 1/10*min(c(a,b))
xb0 = c(1/3*b-bsize,1/3*b-bsize,1/3*b)
yb0 = c(-1/3*a,-1/3*a+bsize,-1/3*a+bsize)

ang = atan(a/b)
tbump = 1/10*max(c(a,b))
xt0 = c(-1/6*b,1/3*b+tbump,-1/6*b-sin(ang)*tbump)
yt0 = c(-1/3*a-tbump,1/6*a,1/6*a+cos(ang)*tbump)

th = runif(1,0,2*pi)

if(sample(1:2,1)==2){
    x0 = -x0
    xb0 = -xb0
    xt0 = -xt0
}


x1 = cos(th)*x0-sin(th)*y0
y1 = sin(th)*x0+cos(th)*y0
xb1 = cos(th)*xb0-sin(th)*yb0
yb1 = sin(th)*xb0+cos(th)*yb0
xt1 = cos(th)*xt0-sin(th)*yt0
yt1 = sin(th)*xt0+cos(th)*yt0

par(mar=c(0,0,0,0),pty="s")
plot(0,0,"n",axes=F,ann=F,xlim=c(-r0max,r0max),ylim=c(-r0max,r0max))

polygon(x1,y1,lwd=2)
lines(xb1,yb1,lwd=1)

text(xt1,yt1,c("?",a,c))

```
\

The tolerance is $\pm 0.1$.


Solution
========

Use pythagorean theorem.

$$a=`r a`$$
$$c=`r c`$$

$a^2+b^2=c^2$


$b^2=c^2-a^2$

$$b = \sqrt{c^2-a^2}$$

$$b = \sqrt{{`r c`}^2-{`r a`}^2}$$


$$b\approx `r sprintf("%0.2f",b)`$$




Meta-information
============
extype: num
exsolution: `r b`
exname: pyth_thrm_get_leg
extol: 0.1