---
output: pdf_document
params:
    rseed: 2
    showsol: false
---

\renewcommand{\arraystretch}{1.2}

```{r,echo=F,warning=FALSE,message=FALSE}
options(scipen=999)
if(params$rseed !=0){
    set.seed(params$rseed)
}
knitr::opts_chunk$set(echo = FALSE)
bn <- basename(knitr::current_input())
bn = strsplit(bn,".",fixed=T)[[1]][1]

pn = function(coeffs,pows){
    pows = pows[coeffs!=0]
    coeffs = coeffs[coeffs!=0]
    ex1 = paste0("{",coeffs,"}x^{",pows,"}",collapse="+")
    ex1 = gsub("+{-","-{",ex1,fixed=T)
    ex1 = gsub("{1}x^{0}","1",ex1,fixed=T)
    ex1 = gsub("{-1}x^{0}","-1",ex1,fixed=T)
    ex1 = gsub("{1}x","x",ex1,fixed=T)
    ex1 = gsub("{-1}x","-x",ex1,fixed=T)
    ex1 = gsub("x^{0}","",ex1,fixed=T)
    ex1 = gsub("x^{1}","x",ex1,fixed=T)
    ex1 = gsub("+-","-",ex1,fixed=T)
    if(ex1 == ""){
        ex1 = "0"
    }
    ex1 = gsub("{","",ex1,fixed=T)
    ex1 = gsub("}","",ex1,fixed=T)
    return(ex1)
}
```

## `r bn`

### Q1 practice

```{r,echo=F}
rat_pairs = list(c(1,1),c(1,2),c(1,3),c(1,4),c(1,5),c(1,6),c(1,7),c(1,8),c(1,9),
                 c(2,1),c(2,3),c(2,5),c(2,7),c(2,9),
                 c(3,1),c(3,2),c(3,4),c(3,5),c(3,7),c(3,8),
                 c(4,1),c(4,3),c(4,5),c(4,7),c(4,9),
                 c(5,1),c(5,2),c(5,3),c(5,4),c(5,6),c(5,7),c(5,8),c(5,9),
                 c(6,1),c(6,5),c(6,7),
                 c(7,1),c(7,2),c(7,3),c(7,4),c(7,5),c(7,6),c(7,8),c(7,9),
                 c(8,1),c(8,3),c(8,5),c(8,7),c(8,9),
                 c(9,1),c(9,2),c(9,4),c(9,5),c(9,7),c(9,8))

frac1s = character()
frac2s = character()
frac3s = character()
cubics = character()
factoreds = character()

while(length(cubics)<10){
    while(T){
        rps = sample(rat_pairs,3)
        a = rps[[1]][1]
        b = rps[[1]][2]*sample(c(-1,1),1)
        c = rps[[2]][1]
        d = rps[[2]][2]*sample(c(-1,1),1)
        e = rps[[3]][1]
        f = rps[[3]][2]*sample(c(-1,1),1)
        A = a*c*e
        B = a*c*f+a*d*e+b*c*e
        C = a*d*f+b*c*f+b*d*e
        D = b*d*f
        p = c*e
        q = c*f+d*e
        r = d*f
        p2 = a*e
        q2 = a*f+b*e
        r2 = b*f
        p3 = a*c
        q3 = a*d+b*c
        r3 = b*d
        cfs = c(a,b,c,d,e,f,A,B,C,D,p,q,r)
        cubic = pn(c(A,B,C,D),3:0)
        if(min(abs(cfs))>0 && max(abs(cfs))<1000 && max(c(c,e))>1 && a>1 && A!=D && abs(sum(sign(c(b,d,f))))<3 && !(cubic %in% cubics)){break}
    }
    
    mkfrac = function(top,bot){
        if(bot>1){
            return(paste0("\\frac{",top,"}{",bot,"}"))
        } else {
            return(paste0(top))
        }
    }
    f1 = pn(c(a,b),1:0)
    f2 = pn(c(c,d),1:0)
    f3 = pn(c(e,f),1:0)
    frac1 = mkfrac(-b,a)
    frac2 = mkfrac(-d,c)
    frac3 = mkfrac(-f,e)
    frac1s = c(frac1s,frac1)
    frac2s = c(frac2s,frac2)
    frac3s = c(frac3s,frac3)
    cubics = c(cubics,cubic)
    factoreds = c(factoreds,paste0(paste0("(",c(f3,f2,f1),")",collapse=""),"=0"))
}

```


```{r,echo=F,results='asis'}
for(i in 1:length(cubics)){
    frac1 = frac1s[i]
    frac2 = frac2s[i]
    frac3 = frac3s[i]
    cat(paste0(i,". A cubic equation has the following solutions: $x=",frac3,"$ and $x=",frac2,"$ and $x=",frac1,"$. The equation is in standard form, with a positive cubic coefficient that is as small as possible. Find the equation.\n\n\\vfill\n\n"))
}
```

\newpage

### Solutions to Q1 practice

```{r,echo=F,results='asis'}
for(i in 1:length(cubics)){
    cubic = cubics[i]
    factored = factoreds[i]
    cat(paste0(i,". The factored form is $",factored,"$. The standard form equation (the answer) is: $$",cubic,"=0$$\n\n\\vfill\n\n"))
}
```

\newpage


### Q2 practice

```{r,echo=F}
rat_pairs = list(c(1,1),c(1,2),c(1,3),c(1,4),c(1,5),c(1,6),c(1,7),c(1,8),c(1,9),
                 c(2,1),c(2,3),c(2,5),c(2,7),c(2,9),
                 c(3,1),c(3,2),c(3,4),c(3,5),c(3,7),c(3,8),
                 c(4,1),c(4,3),c(4,5),c(4,7),c(4,9),
                 c(5,1),c(5,2),c(5,3),c(5,4),c(5,6),c(5,7),c(5,8),c(5,9),
                 c(6,1),c(6,5),c(6,7),
                 c(7,1),c(7,2),c(7,3),c(7,4),c(7,5),c(7,6),c(7,8),c(7,9),
                 c(8,1),c(8,3),c(8,5),c(8,7),c(8,9),
                 c(9,1),c(9,2),c(9,4),c(9,5),c(9,7),c(9,8))

mkfrac = function(top,bot){
        if(bot>1){
            return(paste0("\\frac{",top,"}{",bot,"}"))
        } else {
            return(paste0(top))
        }
}
frac1s = character()
frac2s = character()
frac3s = character()
f1s = character()
cubics = character()
factoreds = character()

while(length(cubics)<10){
    while(T){
        rps = sample(rat_pairs,3)
        a = rps[[1]][1]
        b = rps[[1]][2]*sample(c(-1,1),1)
        c = rps[[2]][1]
        d = rps[[2]][2]*sample(c(-1,1),1)
        e = rps[[3]][1]
        f = rps[[3]][2]*sample(c(-1,1),1)
        A = a*c*e
        B = a*c*f+a*d*e+b*c*e
        C = a*d*f+b*c*f+b*d*e
        D = b*d*f
        p = c*e
        q = c*f+d*e
        r = d*f
        cfs = c(a,b,c,d,e,f,A,B,C,D,p,q,r)
        cubic = pn(c(A,B,C,D),3:0)
        if(min(abs(cfs))>0 && max(abs(cfs))<100 && max(c(c,e))>1 && a==1 && abs(b)>1 && !(cubic %in% cubics)){break}
    }
    f1 = pn(c(a,b),1:0)
    f2 = pn(c(c,d),1:0)
    f3 = pn(c(e,f),1:0)
    frac1 = mkfrac(-b,a)
    frac2 = mkfrac(-d,c)
    frac3 = mkfrac(-f,e)
    frac1s = c(frac1s,frac1)
    frac2s = c(frac2s,frac2)
    frac3s = c(frac3s,frac3)
    cubics = c(cubics,cubic)
    f1s = c(f1s,f1)
}
```


```{r,echo=F,results='asis'}
for(i in 1:length(cubics)){
    cat(paste0(i,". Find the three distinct rational solutions to the given cubic equation. Hint: one factor is $",f1s[i],"$. $$",cubics[i],"=0$$ \n\n\\vfill\n\n"))
}
```

\newpage

### Q2 Solutions

```{r,echo=F,results='asis'}
for(i in 1:length(cubics)){
    cat(paste0(i,". The solutions are $x=",frac1s[i],"$ and $x=",frac2s[i],"$ and $x=",frac3s[i],"$.\n\n\\vfill\n\n"))
}
```




