---
output: pdf_document
params:
    rseed: 1
    showsol: true
header-includes:
  - \usepackage{multicol}
---

```{r,echo=F,warning=FALSE,message=FALSE}
options(scipen=999)
if(params$rseed !=0){
    set.seed(params$rseed)
}
knitr::opts_chunk$set(echo = FALSE)
bn <- basename(knitr::current_input())
bn = strsplit(bn,".",fixed=T)[[1]][1]
```

## `r bn`

```{r}
gcd2 <- function(a, b) {
  if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))
```


```{r,echo=FALSE}

# sqrt(x+a)+b = sqrt(x+c)
# x+a + 2b*sqrt(x+a) + b^2 = x+c
# sqrt(x+a) = (c-a-b^2)/(2b)
# x+a = (c-a-b^2)^2/(4b^2)
# x = (c-a-b^2)^2/(4b^2)-a

isval = sample(c(T,F),1)
if(isval){
    ans2 = "valid"
} else {
    ans2 = "extraneous"
}

while(T){
    abc = sample(2:9,3)*sample(c(-1,1),3,T)
    a = abc[1]
    b = abc[2]
    c = abc[3]
    xposs = (c-a-b^2)^2/(4*b^2)-a
    ls = sqrt(xposs+a)+b
    rs = sqrt(xposs+c)
    if((ls==rs)==isval && xposs%%1==0 && abs(xposs)<100 && abs(c-a-b^2)>0){break}
}
eq = paste0("\\sqrt{x+",a,"}+",b,"=\\sqrt{x+",c,"}")
eq = gsub("+-","-",eq,fixed=T)

ans21 = ans2

abc1 = abc

```

Using algebra, find the possible solution, and determine whether the solution is valid or extraneous.

$$`r eq`$$

\vspace{1in}

```{r,echo=F,results="asis",eval=params$showsol}
cat("\\color{red}")

cat("\n\nSquare both sides.\n")

eq = paste0("(\\sqrt{x+",a,"}+",b,")^2=(\\sqrt{x+",c,"})^2")
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

cat("\n\nThe left side will need to be FOILed. On the right side, the inverse operations cancel out.\n\n")

eq = paste0("(\\sqrt{x+",a,"}+",b,")(\\sqrt{x+",a,"}+",b,")=x+",c)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

eq = paste0("(x+",a,")+",b,"\\sqrt{x+",a,"}+",b,"\\sqrt{x+",a,"}+(",b,")^2=x+",c)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

eq = paste0("x+",a,"+",2*b,"\\sqrt{x+",a,"}+",b^2,"=x+",c)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

cat("\nIsolate the radical.")

# cat(paste0("Subtract $x+",a,"+",b^2,"$ from both sides.\n\n"))

eq = paste0(2*b,"\\sqrt{x+",a,"}=",c-a-b^2)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

# cat(paste0("Divide both sides by $",2*b,"$.\n\n"))

eq = paste0("\\sqrt{x+",a,"}=",round((c-a-b^2)/(2*b)))
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

cat("Square both sides.\n\n")

eq = paste0("x+",a,"=",round((c-a-b^2)/(2*b))^2)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))


# if(a>0){
#     cat("Subtract ",a," from both sides.")
# } else {
#     cat("Add ",-a," to both sides.")
# }

eq = paste0("x=",round((c-a-b^2)/(2*b))^2-a)
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

cat(paste0("So, our possible solution is $x=",round((c-a-b^2)/(2*b))^2-a,"$. We need to check if this satisfies the given equation."))


eq = paste0("\\sqrt{",xposs,"+",a,"}+",b,"\\stackrel{?}{=}\\sqrt{",xposs,"+",c,"}")
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

eq = paste0("\\sqrt{",xposs+a,"}+",b,"\\stackrel{?}{=}\\sqrt{",xposs+c,"}")
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

eq = paste0(sqrt(xposs+a),"+",b,"\\stackrel{?}{=}",sqrt(xposs+c))
eq = gsub("+-","-",eq,fixed=T)
cat(paste0("$$",eq,"$$\n\n"))

if(isval){
    eq = paste0(sqrt(xposs+a)+b,"=",sqrt(xposs+c))
    eq = gsub("+-","-",eq,fixed=T)
    cat(paste0("$$",eq,"$$\n\n"))
    cat(paste0("So, the possible solution $x=",xposs,"$ is valid."))
} else {
    eq = paste0(sqrt(xposs+a)+b,"\\ne ",sqrt(xposs+c))
    eq = gsub("+-","-",eq,fixed=T)
    cat(paste0("$$",eq,"$$\n\n"))
    cat(paste0("So, the possible solution $x=",xposs,"$ is extraneous."))
}

```

\color{black}

\newpage

```{r,echo=FALSE}
n = 18
eqs = character()
sols = character()
vals = sample(c(T,F),n,T)

while(length(eqs)<n){
    isval = vals[length(eqs)+1]
    if(isval){
        ans2 = "valid"
    } else {
        ans2 = "extraneous"
    }
    while(T){
        abc = sample(2:9,3)*sample(c(-1,1),3,T)
        a = abc[1]
        b = abc[2]
        c = abc[3]
        xposs = (c-a-b^2)^2/(4*b^2)-a
        ls = sqrt(xposs+a)+b
        rs = sqrt(xposs+c)
        if((ls==rs)==isval && xposs%%1==0 && abs(xposs)<100 && abs(c-a-b^2)>0){break}
    }
    eq = paste0("\\sqrt{x+",a,"}+",b,"=\\sqrt{x+",c,"}")
    eq = gsub("+-","-",eq,fixed=T)
    ans21 = ans2
    abc1 = abc
    if(isval){
        sol = paste0("x=",xposs," \\text{ is valid.}")
    } else {
        sol = paste0("x=",xposs," \\text{ is extraneous.}")
    }
    if(!(eq %in% eqs)){
        eqs = c(eqs,eq)
        sols = c(sols,sol)
    }
}

```


```{r,echo=F,results='asis'}

s = ""
for(i in 1:length(eqs)){
    s = paste0(s,eqs[i])
    if(i%%2==0 && i<length(eqs)){
        s = paste0(s," \\\\\n\\\\\n")
    } else {
        s = paste0(s," && ")
    }
}

cat(paste0("\\begin{align*}\n"))
cat(s)
cat(paste0("\n\\end{align*}"))

```

\vfill

```{r,echo=F,results='asis'}
s = ""
for(i in 1:length(sols)){
    s = paste0(s,sols[i])
    if(i%%2==0 && i<length(sols)){
        s = paste0(s," \\\\\n\\\\\n")
    } else {
        s = paste0(s," && ")
    }
}
cat("\\color{gray}\n")
cat("### Answers\n\n")
cat(paste0("\\begin{align*}\n"))
cat(s)
cat(paste0("\n\\end{align*}"))
cat("\n\\color{black}\n")
```

