```{r,echo=FALSE}
ques = ""
sols = ""

library(latex2exp)

qtexts = character()
atexts = character()

mkdots = function(n,xc=0,yc=0,scale=0.13,radius=0.05){
    th = seq(0,2*pi,pi/30)
    ncol = floor(sqrt(n))
    nrow = ceiling(n/ncol)
    pchlist = 0:13
    for(i in 0:(n-1)){
        hue1 = runif(1,0,1)
        hue2 = runif(1,0,1)
        hue3 = runif(1,0,1)
        r = i%/%ncol
        c = i%%ncol
        x = xc-ncol/2*scale+scale/2+c*scale
        y = yc+nrow/2*scale-scale/2-r*scale
        rrrs = seq(radius,0,length.out=100)
        dir = sample(c(-1,1),1)
        for(kk in 1:length(rrrs)){
            rrr = rrrs[kk]
            hhh = (hue1*(length(rrrs)-kk*dir)/length(rrrs)+hue2*(kk*dir)/length(rrrs))%%1
            polygon(x+rrr*cos(th),y+rrr*sin(th),col=hsv(hhh,1,1),border=F)
        }
        lines(x+radius*cos(th),y+radius*sin(th))
        points(x,y,pch=sample(pchlist,1),cex=1.2,col=hsv(hue3,1,0.5),lwd=2)
    }
}


nums = sample(1:12,4) #c(12,12,12,12) #
a_nb = nums[1]
na_b = nums[2]
a_b = nums[3]
na_nb = nums[4]
a = a_nb+a_b
b = na_b+a_b
u = sum(nums)
aUb = u-na_nb
aIb = a_b
exps = c("A","B","A'","B'",
         "A ∩ B","A' ∩ B","A ∩ B'","A' ∩ B'",
         "A ∪ B","A' ∪ B","A ∪ B'","A' ∪ B'",
         "(A ∩ B)'","(A' ∩ B)'","(A ∩ B')'","(A' ∩ B')'",
         "(A ∪ B)'","(A' ∪ B)'","(A ∪ B')'","(A' ∪ B')'",
         "(A ∩ B')∪(A' ∩ B)","(A ∩ B)∪(A' ∩ B')"
)
lats = c("A","B","A'","B'",
         "A \\cap B","A' \\cap B","A \\cap B'","A' \\cap B'",
         "A \\cup B","A' \\cup B","A \\cup B'","A' \\cup B'",
         "(A \\cap B)'","(A' \\cap B)'","(A \\cap B')'","(A' \\cap B')'",
         "(A \\cup B)'","(A' \\cup B)'","(A \\cup B')'","(A' \\cup B')'",
         "(A \\cap B')\\cup(A' \\cap B)","(A \\cap B)\\cup(A' \\cap B')"
)
nums = c(a,b,u-a,u-b,
         aIb,na_b,a_nb,na_nb,
         aUb,b+na_nb,a+na_nb,u-aIb,
         u-aIb,u-na_b,u-a_nb,u-na_nb,
         u-aUb,u-(b+na_nb),u-(a+na_nb),aIb,
         a_nb+na_b,aIb+na_nb)
wo = sample(1:length(exps),1)
ee = exps[wo]
nn = nums[wo]
ll = lats[wo]


qtexts = c(qtexts,paste0("How many ",ee," ?"))
atexts = c(atexts,nn)
# s = paste0(c(ns,which(ns==nc)),collapse="&")
# sols = paste0(sols,s,"\n")
```


Question
========

There are `r u` tokens organized by 2 (not visible) attributes. Tokens with those attributes are categorized into subsets $A$ and $B$. Those subsets are visualized with a Venn diagram below. Each region's cardinality is shown.

```{r,echo=F,fig.dim=c(4,4)}
par(mar=c(0,0,0,0),pty="s")
plot(0,0,"n",axes=F,ann=F,xlim=c(-1,1.5),ylim=c(-1.5,1))
co = 0.3
ra = 0.6
xc1 = co
yc1 = 0
xc2 = -co
yc2 = 0
th = seq(0,2*pi,pi/100)
for(j in 1:10){
    polygon(xc1+ra*cos(th),yc1+ra*sin(th),col=rgb(1,0,0,0.01))
    polygon(xc2+ra*cos(th),yc2+ra*sin(th),col=rgb(0,0,1,0.01))
}
text(-0.7,0.55,"A",col=rgb(0,0,0.8),cex=1.2)
text(0.7,0.55,"B",col=rgb(0.8,0,0),cex=1.2)
polygon(c(-1,1.5,1.5,-1),c(-0.7,-0.7,0.7,0.7))
text(-0.9,0.95,paste0("n[universal set] = ",u),adj=c(0,1),cex=1.3)
mkdots(a_nb,-0.55,0.1)
mkdots(na_b,0.55,0.1)
mkdots(a_b,0,0.1)
mkdots(na_nb,1.2,0.1)
text(-0.55,-0.35,a_nb,cex=2)
text(0.55,-0.35,na_b,cex=2)
text(0,-0.35,a_b,cex=2)
text(1.2,-0.35,na_nb,cex=2)
q = TeX(paste0("Find  $n\\left[\\,",ll,"\\,\\right]$"))
text(0.25,-1.1,q,cex=1.8)
```
\

Find $n(`r ee`)$.


Solution
========

The answer is `r nn`.

Meta-information
============
extype: num
exsolution: `r nn`
exname: venn_2_dots