```{r,echo=FALSE}
library(reticulate)
options(scipen=999)
ab = sample(2:9,2)
a = ab[1]*sample(c(-1,1),1)
b = ab[2]*sample(c(-1,1),1)
cn = function(a,b){
  cn = gsub("+-","-",paste0(a,"+",b,"i"),fixed=TRUE)
  cn = gsub("0+0i","0",cn,fixed=TRUE)
  cn = gsub("+1i","+i",cn,fixed=TRUE)
  cn = gsub("-1i","-i",cn,fixed=TRUE)
  cn = gsub("+0i","",cn,fixed=TRUE)
  cn = gsub("-0i","",cn,fixed=TRUE)
  if(length(cn)>1 && substr(cn, start = 1, stop = 2)=="0+"){cn = gsub("0+","",cn,fixed=TRUE)}
  if(length(cn)>1 && substr(cn, start = 1, stop = 2)=="0-"){cn = gsub("0-","-",cn,fixed=TRUE)}
  return(cn)
}
cn1 = cn(a,b)


ach = sort(c(cn(a,b),cn(-a,b),cn(a,-b),cn(-a,-b),
             cn(b,a),cn(b,-a),cn(-b,a),cn(-b,-a)))

al = paste0("* $",ach,"$",collapse="\n")
sol = paste0(1*(ach==cn1),collapse="")

```

Question
========

A dot is shown on the [complex plane](https://en.wikipedia.org/wiki/Complex_plane) below.

```{r,fig.dim=c(4,4),echo=FALSE,results="asis"}
par(pty="s",mar=c(0,0,0,0))
plot(0,0,type="n",xlim=c(-10,10),ylim=c(-10,10),lwd=2,ann=F,axes=F)
for(j in seq(-10,10,1)){
    lines(c(j,j),c(-10,10),lwd=0.5,col="grey")
    lines(c(-10,10),c(j,j),lwd=0.5,col="grey")
}
for(j in seq(-10,10,5)){
    lines(c(j,j),c(-10,10),lwd=1,col="darkgrey")
    lines(c(-10,10),c(j,j),lwd=1,col="darkgrey")
    if(j!=0){
        text(j,0,j,adj=c(0.5,1.2),cex=0.8)
        text(0,j,paste0(j,"i"),adj=c(1.2,0.5),cex=0.8)
    }
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)
points(a,b,pch=20,cex=1.3,col="blue")
```
\

What complex number is represented by the dot?

Answerlist
--------

`r al`

Solution
========

The horizontal (real) component is `r a`. The vertical (imaginary) component is `r b`. So, the dot represents $`r cn1`$.


Meta-information
============
extype: schoice
exsolution: `r sol`
exname: read_complex_plot