---
output: pdf_document
header-includes:
      - \usepackage{calligra}
geometry: margin=1in, paperheight=17in,paperwidth=11in
params:
    rseed: 0
    showsol: true
---

\pagenumbering{gobble}


```{r,echo=F}
gcd2 <- function(a, b) {
  if (b == 0) a else Recall(b, a %% b)
}
gcd <- function(...) Reduce(gcd2, c(...))
pn = function(coeffs,pows){
    pows = pows[coeffs!=0]
    coeffs = coeffs[coeffs!=0]
    ex1 = paste0("{",coeffs,"}x^{",pows,"}",collapse="+")
    ex1 = gsub("+{-","-{",ex1,fixed=T)
    ex1 = gsub("{1}x^{0}","1",ex1,fixed=T)
    ex1 = gsub("{-1}x^{0}","-1",ex1,fixed=T)
    ex1 = gsub("{1}x","x",ex1,fixed=T)
    ex1 = gsub("{-1}x","-x",ex1,fixed=T)
    ex1 = gsub("x^{0}","",ex1,fixed=T)
    ex1 = gsub("x^{1}","x",ex1,fixed=T)
    ex1 = gsub("+-","-",ex1,fixed=T)
    if(ex1 == ""){
        ex1 = "0"
    }
    return(ex1)
}

fsimp = function(top,bot){
    gg = abs(gcd(c(top,bot)))
    top = round(abs(top)/gg*sign(top*bot))
    bot = round(abs(mbot)/gg)
    if(bot==1){
        return(paste0(top))
    } else {
        return(paste0("\\frac{",top,"}{",bot,"}"))
    }
}

xpar = c(0,1,4,9)
ypar = c(0,1,2,3)
xext = c(1,4,9)
yext = c(-1,-2,-3)
h = sample(c(-9:-1,1),1)
a = sample(c(-3,-2,-1,1,2,3),1)
k = sample(c(((-10+3*abs(a)):-1),(1:(10-3*abs(a)))),1)
b = sample(c(-1,1),1)
xc = (xpar+h)/b
yc = a*ypar+k
xd = (xext+h)/b
yd = k+a*yext

nval = 1 #sample(0:2,1)

if(nval==0){
    ii = sample(1:length(xd),2)
    xi = xd[ii]
    yi = yd[ii]
    isval = c(F,F)
    wrd = c("an extraneous","an extraneous")
}
if(nval==1){
    while(T){
        ic = sample(1:length(xc),1)
        id = sample(1:length(xd),1)
        xic = xc[ic]
        yic = yc[ic]
        xid = xd[id]
        yid = yd[id]
        ii = sample(1:2)
        xi = c(xic,xid)[ii]
        yi = c(yic,yid)[ii]
        isval = c(T,F)[ii]
        wrd = c("a valid","an extraneous")[ii]
        if(xic!=xid){break}
    }
}
if(nval==2){
    ii = sample(1:length(xc),2)
    xi = xc[ii]
    yi = yc[ii]
    isval = c(T,T)
    wrd = c("a valid","a valid")
}

mtop = diff(yi)
mbot = diff(xi)
mf = fsimp(mtop,mbot)


while(T){
    xp = sample(-10:10,1)
    yp = mtop*(xp-xi[1])/mbot+yi[1]
    if(abs(yp)<=10 && abs(yp)%%1==0 && yp!=yi[1] && yp!=yi[2] && min(abs(c(xp,yp)))>0){break}
}

if(b==-1){
    fx = paste0(k,"+[",a,"]\\sqrt{-x+",-h,"}")
    gx = paste0(k,"+[",-a,"]\\sqrt{-x+",-h,"}")
} else {
    fx = paste0(k,"+[",a,"]\\sqrt{x+",-h,"}")
    gx = paste0(k,"+[",-a,"]\\sqrt{x+",-h,"}")
}
fx = gsub("[1]","",fx,fixed=T)
fx = gsub("[-1]","-",fx,fixed=T)
fx = gsub("[","",fx,fixed=T)
fx = gsub("]","",fx,fixed=T)
fx = gsub("+-","-",fx,fixed=T)
gx = gsub("[1]","",gx,fixed=T)
gx = gsub("[-1]","-",gx,fixed=T)
gx = gsub("[","",gx,fixed=T)
gx = gsub("]","",gx,fixed=T)
gx = gsub("+-","-",gx,fixed=T)
Lx = paste0("[",mf,"](x+",-xp,")+",yp)
Lx = gsub("+-","-",Lx,fixed=T)
Lx = gsub("[1]","",Lx,fixed=T)
Lx = gsub("[-1]","-",Lx,fixed=T)
Lx = gsub("[","",Lx,fixed=T)
Lx = gsub("]","",Lx,fixed=T)
```

\calligra{\Huge{Radical Equation with Extraneous Solution Example `r params$rseed`}}

\huge
$$`r fx`~=~`r Lx`$$
\normalsize
\rm


\hrule

### Instructions:

1. Label the axes, draw the three functions listed below, and make a clear legend.
    * $y=`r fx`$.
    * $y=`r gx`$.
    * $y=`r Lx`$.
2. Find possible solutions, and state whether each is valid or extraneous.

\hrule

\vspace{1in}

```{r,echo=F,fig.dim=c(9,9)}
par(pty="s",mar=c(0,0,0,0))
plot(0,0,"n",xlim=c(-10,10),ylim=c(-10,10),ann=F,axes=F)

for(i in -10:10){
    lines(c(i,i),c(-10,10),col="grey",lwd=0.5)
    lines(c(-10,10),c(i,i),col="grey",lwd=0.5)
}
for(i in seq(-10,10,5)){
    lines(c(i,i),c(-10,10),col="darkgrey",lwd=1)
    lines(c(-10,10),c(i,i),col="darkgrey",lwd=1)
}
abline(h=0,lwd=2)
abline(v=0,lwd=2)



if(params$showsol){
    text(10,0,"x",adj=c(-0.2,-0.2))
    text(0,10,"y",adj=c(-0.2,-0.2))
    text(10,0,"10",adj=c(0.5,1.2),cex=0.7)
    text(0,10,"10",adj=c(1.1,0.5),cex=0.7)
    xx = seq(h*sign(b),10*sign(b),0.01*sign(b))
    yy = a*sqrt(b*xx-h)+k
    
    xx = xx[abs(yy)<=10]
    yy = yy[abs(yy)<=10]
    
    
    lines(xx,yy,col="blue",lwd=2)
    
    x2 = (c(0,1,4,9,16)+h)/b
    y2 = a*c(0,1,2,3,4)+k
    x2 = x2[abs(y2)<=10]
    y2 = y2[abs(y2)<=10]
    
    points(x2,y2,pch=19,col="blue")
    
    xl = seq(-10,10,0.1)
    yl = mtop/mbot*(xl-xi[1])+yi[1]
    xl = xl[abs(yl)<=10]
    yl = yl[abs(yl)<=10]
    lines(xl,yl,col="red",lwd=2)

    xx = seq(h*sign(b),10*sign(b),0.01*sign(b))
    yy = -a*sqrt(b*xx-h)+k
    
    xx = xx[abs(yy)<=10]
    yy = yy[abs(yy)<=10]
    
    lines(xx,yy,col="grey",lwd=2,lty=2)
    
    points(xi,yi,pch=19,col="red")
    points(xp,yp,pch=19,col="red")
}
```

\vfill

```{r,echo=F,results="asis"}
if(params$showsol){
    cat("\\color{red}\n\n")
    cat(paste0("Possible solution $x=",xi[1],"$ is ",wrd[1]," solution. And $x=",xi[2],"$ is ",wrd[2]," solution.\n",collapse=""))
    cat("\n\n\\color{black}\n\n")
}
```

\vfill

