```{r,echo=FALSE}
pn = function(c,d){
    cc = c[c!=0]
    dd = d[c!=0]
    p = paste0("{",cc,"}x^{",dd,"}",collapse="+")
    p = gsub("x^{0}","",p,fixed=T)
    p = gsub("x^{1}","x",p,fixed=T)
    p = gsub("+{-","-{",p,fixed=T)
    p = gsub("+{1}x","+x",p,fixed=T)
    p = gsub("-{1}x","-x",p,fixed=T)
    p = gsub("{-1}x","-x",p,fixed=T)
    p = gsub("{1}x","x",p,fixed=T)
    return(p)
}

as = sample(c(2,3,1/2,1/3,1/4,1/9),2)*sample(c(-1,1),2)
a = as[1]
while(T){
    rs = sample(1:9,2)*sample(c(-1,1),2,T)
    r = rs[1]
    s = rs[2]
    if(abs(a)>1){
        eq = paste0(a,"(",pn(c(1,-r),1:0),")(",pn(c(1,-s),1:0),")",collapse="")
    } else {
        eq = paste0("\\frac{",sign(a),"}{",abs(round(1/a)),"}(",pn(c(1,-r),1:0),")(",pn(c(1,-s),1:0),")",collapse="")
    }
    h = (r+s)/2
    w = abs(r-s)/2
    k = round(-a*w^2,5)
    if(abs(k)<11 && abs(k)%%1==0 && abs(h)%%1==0){break}
}

eqposs = character()
for(aa in c(as,-as)){
    for(rr in c(-r,r)){
        for(ss in c(-s,s)){
            if(abs(aa)>1){
                eqposs=c(eqposs,paste0(aa,"(",pn(c(1,-rr),1:0),")(",pn(c(1,-ss),1:0),")",collapse=""))
            } else {
                eqposs=c(eqposs,paste0("\\frac{",sign(aa),"}{",round(1/aa),"}(",pn(c(1,-rr),1:0),")(",pn(c(1,-ss),1:0),")",collapse=""))
            }
            
        }
    }
}
eqposs = sort(unique(eqposs))

sol = paste0(1*(eq==eqposs),collapse="")

al = paste0("* $y=",eqposs,"$",collapse="\n")

```

Question
========

A quadratic function, with two [real](https://en.wikipedia.org/wiki/Real_number) [roots](https://en.wikipedia.org/wiki/Zero_of_a_function), is graphed below.

```{r,echo=F,fig.dim=c(4,4)}
par(mar=c(0,0,0,0),pty="s")
plot(0,0,"n",xlim=c(-11,11),ylim=c(-11,11),axes=F,ann=F)
plot(0,0,"n",xlim=c(-11,11),ylim=c(-11,11),axes=F,ann=F)
for(j in -10:10){
    lines(c(-10,10),c(j,j),col="grey",lwd=0.5)
    lines(c(j,j),c(-10,10),col="grey",lwd=0.5)
}
for(j in seq(-10,10,5)){
    lines(c(-10,10),c(j,j),col="darkgrey",lwd=1)
    lines(c(j,j),c(-10,10),col="darkgrey",lwd=1)
}
arrows(-11,0,11,0,0.05,20,3,lwd=1.5)
arrows(0,-11,0,11,0.05,20,3,lwd=1.5)
text(10,0,"10",adj=c(0.5,1.2))
text(0,10,"10",adj=c(1.2,0.5))
text(10,0,"x",adj=c(-0.2,-0.5))
text(0,10,"y",adj=c(-0.5,-0.2))

x = seq(-10,10,0.01)
y = a*(x-r)*(x-s)
x = x[abs(y)<=10]
y = y[abs(y)<=10]
lines(x,y,col="blue",lwd=2)
x = seq(-10,10,1)
y = a*(x-r)*(x-s)
x = x[abs(y)%%1==0]
y = y[abs(y)%%1==0]
points(x,y,col="blue",pch=19)

```
\

What equation represents the function in factored form?

Answerlist
--------

`r al`

Solution
========

The correct answer is:
$$y=`r eq`$$

You can determine $a$ based on [this reference sheet]().




Meta-information
============
extype: cloze
exclozetype: schoice|schoice|schoice
exsolution:
exname: hk_from_factored